# Generated by Django 5.1.4 on 2025-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('cuisine_type', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('lowest_price', models.FloatField(default=0.0)),
                ('highest_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
