# Generated by Django 5.1.4 on 2025-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
