# Generated by Django 5.1.4 on 2025-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_category_menuitem_table_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant_images'),
        ),
    ]
