# Generated by Django 5.1.4 on 2025-01-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_end_time_slot_time_remove_slot_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisine_type',
            new_name='cuisine',
        ),
    ]
