# Generated by Django 5.1.4 on 2025-03-04 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='cuisine_images/')),
                ('keyword', models.TextField(help_text='Keywords for searching cuisines')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='savedrestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
