# Generated by Django 5.1.4 on 2025-04-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
