# Generated by Django 5.1.4 on 2025-04-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_add_user_to_restaurant'),
        ('restaurants', '0015_alter_restaurant_cuisine'),
    ]

    operations = [
    ]
